{ inputs, pkgs, lib, config, ... }:
{
  imports = [
    inputs.caelestia-shell.homeManagerModules.default
  ];

  qt = {
    enable = true;
  };

  programs.caelestia = {
    enable = true;
    cli = {
      enable = true;
      settings = {
        theme = {
          # Live-sync the Material You palette to terminals, Hyprland and GTK.
          # The palette derives from the wallpaper (dynamic scheme), so the
          # built-in wallpaper picker drives all of this automatically.
          enableTerm = true;
          enableHypr = true;
          enableGtk = true;
          # Disable integrations we don't use
          enableQt = false;
          enableDiscord = false;
          enableSpicetify = false;
          enablePandora = false;
          enableFuzzel = false;
          enableBtop = false;
          enableNvtop = false;
          enableHtop = false;
          enableWarp = false;
          enableChromium = false;
          enableZed = false;
          enableCava = false;
          iconTheme = "Papirus-Dark-Maia";
          # Reload hyprland so it picks up hypr/scheme/current.lua, and poke
          # alacritty so it re-reads the generated theme file
          postHook = "hyprctl reload && touch ~/.config/alacritty/theme-trigger.toml";
        };
      };
    };
    settings = {
      # Mirrors the previously hand-written ~/.config/caelestia/shell.json.
      # One deliberate change: wallpaper rendering must be on now that awww
      # is removed (caelestia renders the wallpaper itself).
      background.wallpaperEnabled = true;
      bar.entries = [
        { id = "logo"; }
        { id = "idleInhibitor"; }
        { id = "workspaces"; enabled = false; }
        { id = "activeWindow"; enabled = false; }
        { id = "spacer"; }
        { id = "tray"; }
        { id = "clock"; }
        { id = "statusIcons"; }
        { id = "power"; }
      ];
      dashboard.enabled = false;
      services.useTwelveHourClock = false;
      sidebar.enabled = false;
    };
  };

  # The shell.json was previously hand-written; the settings above mirror it
  # exactly (only wallpaperEnabled changed), so it's safe to take it over.
  xdg.configFile."caelestia/shell.json".force = true;

  # Copy the generated shell.json to a regular file so the shell can persist
  # UI changes and hand-edits work (until the next switch replaces it).
  home.activation.caelestiaShellJson = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    rm -f ~/.config/caelestia/shell.json
    install -m 600 ${config.xdg.configFile."caelestia/shell.json".source} ~/.config/caelestia/shell.json
  '';

  # Templates rendered by `caelestia theme` into ~/.local/state/caelestia/theme/
  home.file.".config/caelestia/templates/alacritty.toml".text = ''
    # Generated by `caelestia theme` from the current Material You palette
    [colors.primary]
    background = "0x{{ surface.hex }}"
    foreground = "0x{{ onSurface.hex }}"

    [colors.cursor]
    text = "0x{{ surface.hex }}"
    cursor = "0x{{ primary.hex }}"

    [colors.selection]
    text = "0x{{ onPrimaryContainer.hex }}"
    background = "0x{{ primaryContainer.hex }}"

    [colors.normal]
    black = "0x{{ term0.hex }}"
    red = "0x{{ term1.hex }}"
    green = "0x{{ term2.hex }}"
    yellow = "0x{{ term3.hex }}"
    blue = "0x{{ term4.hex }}"
    magenta = "0x{{ term5.hex }}"
    cyan = "0x{{ term6.hex }}"
    white = "0x{{ term7.hex }}"

    [colors.bright]
    black = "0x{{ term8.hex }}"
    red = "0x{{ term9.hex }}"
    green = "0x{{ term10.hex }}"
    yellow = "0x{{ term11.hex }}"
    blue = "0x{{ term12.hex }}"
    magenta = "0x{{ term13.hex }}"
    cyan = "0x{{ term14.hex }}"
    white = "0x{{ term15.hex }}"
  '';
  home.file.".config/caelestia/templates/nvim.lua".text = ''
    -- Generated by `caelestia theme` from the current Material You palette
    return {
      mode = "{{ mode }}",
      background = "{{ background.hex }}",
      surface = "{{ surface.hex }}",
      surfaceContainer = "{{ surfaceContainer.hex }}",
      surfaceContainerLow = "{{ surfaceContainerLow.hex }}",
      surfaceContainerHigh = "{{ surfaceContainerHigh.hex }}",
      onSurface = "{{ onSurface.hex }}",
      onSurfaceVariant = "{{ onSurfaceVariant.hex }}",
      primary = "{{ primary.hex }}",
      onPrimary = "{{ onPrimary.hex }}",
      primaryContainer = "{{ primaryContainer.hex }}",
      onPrimaryContainer = "{{ onPrimaryContainer.hex }}",
      secondary = "{{ secondary.hex }}",
      tertiary = "{{ tertiary.hex }}",
      onTertiary = "{{ onTertiary.hex }}",
      error = "{{ error.hex }}",
    }
  '';

  # Wallpapers for the built-in picker
  home.file."Pictures/Wallpapers/fy_bnb.webp".source = ./wallpapers/fy_bnb.webp;
  home.file."Pictures/Wallpapers/fixedimmortaltravel.webp".source = ./wallpapers/fixedimmortaltravel.webp;
  home.file."Pictures/Wallpapers/derrickdoors.webp".source = ./wallpapers/derrickdoors.webp;
  home.file."Pictures/Wallpapers/kleinsmile.webp".source = ./wallpapers/kleinsmile.webp;

  home.packages = [
    pkgs.adw-gtk3 # gtk theme set by `caelestia theme` (apply_gtk)
  ];
}
