require("binds")
require("config")
require("animations")
require("rules")
require("host-config")

hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user start easyeffects.service")
	hl.exec_cmd("systemctl --user start caelestia.service")
	hl.exec_cmd("hyprctl dispatch workspace 1")
end)
